export const variableDescriptions: { [key: string]: string } = {
  Curricular_units_2nd_sem_approved: "Número de materias aprobadas en el segundo semestre",
  Curricular_units_2nd_sem_grade: "Promedio de calificaciones del segundo semestre (escala 0-20)",
  Curricular_units_1st_sem_approved: "Número de materias aprobadas en el primer semestre",
  Curricular_units_1st_sem_grade: "Promedio de calificaciones del primer semestre (escala 0-20)",
  Curricular_units_1st_sem_credited: "Materias convalidadas por estudios previos en primer semestre",
  Curricular_units_1st_sem_enrolled: "Número de materias inscritas en primer semestre",
  Curricular_units_1st_sem_evaluations: "Número total de evaluaciones realizadas en primer semestre",
  Curricular_units_1st_sem_without_evaluations: "Materias sin evaluación en primer semestre",
  Curricular_units_2nd_sem_credited: "Materias convalidadas en segundo semestre",
  Curricular_units_2nd_sem_enrolled: "Materias inscritas en segundo semestre",
  Curricular_units_2nd_sem_evaluations: "Evaluaciones realizadas en segundo semestre",
  Curricular_units_2nd_sem_without_evaluations: "Materias sin evaluación en segundo semestre",
  Tuition_fees_up_to_date: "Indica si el estudiante está al día con el pago de matrícula",
  Debtor: "Indica si el estudiante tiene deudas con la institución",
  Scholarship_holder: "Indica si el estudiante tiene beca",
  Educational_special_needs: "Indica si tiene necesidades educativas especiales o discapacidad",
  Age_at_enrollment: "Edad del estudiante al momento de inscribirse en la universidad",
  Gender: "Género del estudiante",
  Marital_status: "Estado civil del estudiante (Soltero, Casado, Viudo, etc.)",
  Nacionality: "País de origen del estudiante",
  Displaced: "Indica si el estudiante vive lejos de su lugar de origen/familia",
  International: "Indica si el estudiante es extranjero/internacional",
  Application_mode: "Método o vía de ingreso utilizada (contingente general, transferencia, etc.)",
  Application_order: "Preferencia de elección del curso (0=primera opción, 9=última)",
  Course: "Carrera/programa académico en el que se inscribió",
  Daytime_evening_attendance: "Horario de clases (Diurno o Nocturno)",
  Previous_qualification: "Nivel educativo previo del estudiante",
  Mothers_qualification: "Nivel educativo de la madre",
  Fathers_qualification: "Nivel educativo del padre",
  Mothers_occupation: "Profesión u ocupación de la madre",
  Fathers_occupation: "Profesión u ocupación del padre",
  Unemployment_rate: "Tasa de desempleo del país al momento de inscripción",
  Inflation_rate: "Tasa de inflación del país al momento de inscripción",
  GDP: "Producto Interno Bruto del país al momento de inscripción",
  Depression_score: "Puntuación de depresión del estudiante (escala 0-10, donde 10 es más severo)",
  Anxiety_score: "Puntuación de ansiedad del estudiante (escala 0-10, donde 10 es más severo)",
};
