apiVersion: v1
kind: Service
metadata:
  name: desercion-backend
  namespace: desercion
  labels:
    app: desercion-backend
spec:
  type: ClusterIP
  selector:
    app: desercion-backend
  ports:
    - name: http
      port: 8182
      targetPort: 8182
      protocol: TCP
