apiVersion: v1
kind: Service
metadata:
  name: desercion-frontend
  namespace: desercion
  labels:
    app: desercion-frontend
spec:
  type: ClusterIP
  selector:
    app: desercion-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3020
      protocol: TCP
