apiVersion: v1
kind: Secret
metadata:
  name: desercion-secret
  namespace: desercion
type: Opaque
stringData:
  POSTGRES_USER: "desercion_user"
  POSTGRES_PASSWORD: "desercion_password"
  DB_PASSWORD: "desercion_password"
  JWT_SECRET_KEY: "3792f5ded446122f59da372c5ea0ce39b72fbfc7c94af4536de0b53c8f94ae03"
